SAUCE: unconditionally link with openssl.
we are hitting LP#1590782 where build fails with
undefined reference to symbol 'SSL_get_verify_result@@OPENSSL_1.0.0'.
This fix, proposed by tcpcloud has been rejected at the time
by Juniper, so we should track down why is it needed (could be
different librdkafka versions, or even different build environments).